### ISSUE TITLE
模型推断速度

### ISSUE THREAD

**Issue by AlexRainHao** [LeeSureman/Flat-Lattice-Transformer#11]
您好，请问有实验过模型预测的速度吗，我用的一块Tesla P100，每个样本预测速度在5s左右，这个是正常的吗

**Comment by LeeSureman** [comment]
绝对速度没试过，请问您是多少长度的输入？

**Comment by AlexRainHao** [comment]
> 绝对速度没试过，请问您是多少长度的输入？

我解决了，因为我错误的每次输入都重新加载了词向量23333，多谢

**Comment by LeeSureman** [comment]
哈哈哈，恭喜

**Comment by liubo12** [comment]
@AlexRainHao 您好，方便分享一下预测的代码嘛

**Comment by AlexRainHao** [comment]
> @AlexRainHao 您好，方便分享一下预测的代码嘛

麻烦您发我一下邮箱

**Comment by AlexRainHao** [comment]
@liubo12 麻烦您发我一下邮箱

**Comment by liubo12** [comment]
@AlexRainHao 要是能把所有Flat代码都发我一下就更感谢您啦
我的邮箱：736343658@qq.com

**Comment by xbc0112** [comment]
@AlexRainHao 同求一份预测的代码，903597418@qq.com,非常感谢！

**Comment by crazymirror** [comment]
> @AlexRainHao 要是能把所有Flat代码都发我一下就更感谢您啦
> 我的邮箱：[736343658@qq.com](mailto:736343658@qq.com)

这里这里这里 也希望能够得到更全面的代码 感谢大佬 :p 我的邮箱：690879711@qq.com

**Comment by AlexRainHao** [comment]
> > @AlexRainHao 要是能把所有Flat代码都发我一下就更感谢您啦
> > 我的邮箱：[736343658@qq.com](mailto:736343658@qq.com)
> 
> 这里这里这里 也希望能够得到更全面的代码 感谢大佬 :p 我的邮箱：[690879711@qq.com](mailto:690879711@qq.com)

已经发送

**Comment by zh-hongda** [comment]
@AlexRainHao 能否将包含推理的Flat代码发我一份呢？649563933@qq.com

**Comment by zh-hongda** [comment]
@AlexRainHao 能否将包含推理的Flat代码发我一份呢，谢谢！649563933@qq.com

**Comment by zhentaoCoding** [comment]
@AlexRainHao 能否将包含推理的Flat代码发我一份呢,谢谢，邮箱zt950607@foxmail.com

**Comment by MickeyMmmmmouse** [comment]
@AlexRainHao 同求包含推理的代码, 十分感谢, 邮箱   715006478@qq.com

**Comment by konghr** [comment]
@AlexRainHao 同求包含推理的代码, 十分感谢, 邮箱 523024936@qq.com

**Comment by zhoulinmin** [comment]
@AlexRainHao 同求包含推理的代码, 谢谢了, 邮箱 492782950@qq.com

**Comment by MiracleMob** [comment]
@AlexRainHao 同求包含推理的代码, 谢谢了, 邮箱 873609291@qq.com

**Comment by Dashengren** [comment]
您好，在运行代码过程中，发现给出了两个评测指标，span F和Type Acc，普通F1的计算方式是没有给出来吗，即论文Table 2中四个数据集在不同模型上F1指标的评测，这个F1值的计算改怎么算呢？
