### ISSUE TITLE
运行flat_main.py报错

### ISSUE THREAD

**Issue by Zhang-JiaYu** [LeeSureman/Flat-Lattice-Transformer#16]
按照readme运行代码会报以下错误，想请教一下是什么原因造成的：
Traceback (most recent call last):
  File "flat_main.py", line 306, in <module>
    only_train_min_freq=args.only_train_min_freq)
  File "E:\Program\Anaconda\Install\envs\pytorch-1.2.0\lib\site-packages\fastNLP\core\utils.py", line 160, in wrapper
    with open(cache_filepath, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cache\\weibo_lattice_only_train:False_trainClip:True_norm_num:0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100'

**Comment by LeeSureman** [comment]
可以试试在当前目录下新建个cache文件夹

**Comment by YuMo10** [comment]
> 按照readme运行代码会报以下错误，想请教一下是什么原因造成的：
> Traceback (most recent call last):
> File "flat_main.py", line 306, in
> only_train_min_freq=args.only_train_min_freq)
> File "E:\Program\Anaconda\Install\envs\pytorch-1.2.0\lib\site-packages\fastNLP\core\utils.py", line 160, in wrapper
> with open(cache_filepath, 'wb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'cache\weibo_lattice_only_train:False_trainClip:True_norm_num:0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100'

我也是，楼主解决了吗

**Comment by lvjiujin** [comment]
> > 按照readme运行代码会报以下错误，想请教一下是什么原因造成的：
> > Traceback (most recent call last):
> > File "flat_main.py", line 306, in
> > only_train_min_freq=args.only_train_min_freq)
> > File "E:\Program\Anaconda\Install\envs\pytorch-1.2.0\lib\site-packages\fastNLP\core\utils.py", line 160, in wrapper
> > with open(cache_filepath, 'wb') as f:
> > FileNotFoundError: [Errno 2] No such file or directory: 'cache\weibo_lattice_only_train:False_trainClip:True_norm_num:0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100'
> 
> 我也是，楼主解决了吗

肯定是在windows下运行的，文件名不能有冒号。我觉得windows迟早要解决这个问题。
