### ISSUE TITLE
可以发一下数据集的格式吗

### ISSUE THREAD

**Issue by lingdavid** [LeeSureman/Flat-Lattice-Transformer#18]
你好，可以发一下数据集的格式吗，发几条样例数据

**Comment by LawsonAbs** [comment]
同求！麻烦作者告知一下数据格式（能否附网盘下载链接以便复现代码）

**Comment by LawsonAbs** [comment]
> 
> 
> 你好，可以发一下数据集的格式吗，发几条样例数据

数据集的格式就是标准的“序列标注”数据。这里以微博数据集为例，展示部分的数据：
`隘 O
的 O
地 O
方 O
主 O
义 O
， O
所 O
谓 O
的 O
死 B-PER.NOM
忠 I-PER.NOM
们 I-PER.NOM
。 O
`
如果需要本任务全部的微博数据集，可以联系我~
