### ISSUE TITLE
能否将代码发送我邮箱一份？

### ISSUE THREAD

**Issue by 45825529** [LeeSureman/Flat-Lattice-Transformer#2]
拜读了您的论文，感觉是非常好的idea。迫不及待地想看下源码。您能否提前发一份源码到我邮箱，仅供学习之用。email： 45825529@qq.com
非常感谢！

**Comment by leona-hub** [comment]
希望也能发给我一份非常感谢1756652945@qq.com

**Comment by tujie-jiangye** [comment]
希望也能发给我一份非常感谢3293375273@qq.com

**Comment by leona-hub** [comment]
作者也没有发给我，十分抱歉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"徐土杰"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 下午3:36
收件人:&nbsp;"LeeSureman/Flat-Lattice-Transformer"<Flat-Lattice-Transformer@noreply.github.com&gt;;
抄送:&nbsp;".Leona"<1756652945@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LeeSureman/Flat-Lattice-Transformer] 能否将代码发送我邮箱一份？ (#2)





 
希望也能发给我一份非常感谢3293375273@qq.com

**Comment by tujie-jiangye** [comment]
没关系，谢谢

**Comment by LeeSureman** [comment]
你好，代码刚刚发布，请查收

**Comment by Eason-zz** [comment]
您好，我也想参看一下您的论文源码，875804248@qq.com，非常感谢

**Comment by LeeSureman** [comment]
> 您好，我也想参看一下您的论文源码，[875804248@qq.com](mailto:875804248@qq.com)，非常感谢

你好，已经放到这个仓库里了

**Comment by Eason-zz** [comment]
好的，非常感谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeeSureman/Flat-Lattice-Transformer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月29日(星期二) 下午2:15
收件人:&nbsp;"LeeSureman/Flat-Lattice-Transformer"<Flat-Lattice-Transformer@noreply.github.com&gt;;
抄送:&nbsp;"而来"<875804248@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LeeSureman/Flat-Lattice-Transformer] 能否将代码发送我邮箱一份？ (#2)





  
您好，我也想参看一下您的论文源码，875804248@qq.com，非常感谢
  
你好，已经放到这个仓库里了
