### ISSUE TITLE
请问能给出各个测试数据集的地址吗？如果游客知道，也请麻烦告知一下~

### ISSUE THREAD

**Issue by LawsonAbs** [LeeSureman/Flat-Lattice-Transformer#20]
如题。

**Comment by LawsonAbs** [comment]
问题已经解决！
数据集下载地址为：https://github.com/RowitZou/LGN  中Data的部分。
如果有其它代码问题，欢迎和我一起讨论（有效期2个月哦）~

**Comment by WallE-Chang** [comment]
https://github.com/ShannonAI/glyce/blob/master/docs/dataset_download.md 貌似也可以，直接就可以下载全部的

**Comment by Boltzmachine** [comment]
这个里面的msra是train.ner，而代码里用的是train_dev.char.bmes 这种 要怎么处理

**Comment by houyuchao** [comment]
> 这个里面的msra是train.ner，而代码里用的是train_dev.char.bmes 这种 要怎么处理

您好这个问题解决了吗，怎么样处理数据啊
