### ISSUE TITLE
为什么要把所有的加载好的数据集都放到train中，是bug吗？

### ISSUE THREAD

**Issue by LawsonAbs** [LeeSureman/Flat-Lattice-Transformer#22]
在文件load_data.py中489—491行代码【函数 load_weibo_ner()】：
```python
   for k,v in paths.items():
        bundle = loader.load(v)
        datasets[k] = bundle.datasets['train']
```
为什么是把所有的数据都放到 train中？不应该是分别放在dataset[train],dataset[dev] ,dataset[test] 吗？

**Comment by LeeSureman** [comment]
哦~是这样，我每次只用load一个对应的文件，然后fastNLP就默认load一个文件的时候，那个文件的key就是train，然后这里的datasets是一个字典，key分别是train，dev，test

**Comment by LawsonAbs** [comment]
噢噢，明白了，多谢啦~ (*^▽^*)

**Comment by Dashengren** [comment]
您好，在运行代码过程中，发现给出了两个评测指标，span F和Type Acc，普通F1的计算方式是没有给出来吗，即论文Table 2中四个数据集在不同模型上F1指标的评测，这个F1值的计算改怎么算呢？
