### ISSUE TITLE
yangjie_word_char_mix.txt无法打开

### ISSUE THREAD

**Issue by Eason-zz** [LeeSureman/Flat-Lattice-Transformer#23]
处理后生成的这个txt文件无法打开是怎么回事啊，一打开就无响应

**Comment by LawsonAbs** [comment]
老哥，你知道这个文件多大吗？328M， 你用软件打开肯定慢的很啊。。。

**Comment by Eason-zz** [comment]
> 老哥，你知道这个文件多大吗？328M， 你用软件打开肯定慢的很啊。。。

那怎么处理呢，最后结果就只有生成这个文件吗。。。抱歉哈，我是菜鸟还不太懂

**Comment by LeeSureman** [comment]
不用自己打开，程序会读取的

**Comment by Eason-zz** [comment]
> 不用自己打开，程序会读取的

好的谢谢

**Comment by tujie-jiangye** [comment]
yangjie_word_char_mix.txt，老哥，请问这个文件在哪里可以找到

**Comment by LawsonAbs** [comment]
> 
> 
> yangjie_word_char_mix.txt，老哥，请问这个文件在哪里可以找到

这个文件的下载地址 作者已经readme中说清楚了。

**Comment by tujie-jiangye** [comment]
gigaword_chn.all.a2b.uni.ite50.vec/gigaword_chn.all.a2b.bi.ite50.vec/ctb.50d.vec/sgns.merge.word从readme中能够找到这四个，还缺上边的yangjie_word_char_mix.txt，不知道有没有遗漏，老哥方便给个链接吗

**Comment by tujie-jiangye** [comment]
懂了懂了，是程序生成的

**Comment by LawsonAbs** [comment]
> 
> 
> 懂了懂了，是程序生成的

对的，不好意思，我刚才误导你了，我自己刚才想删掉cache，再验证一下的，哪知道不怎么顺利，哈哈哈~

**Comment by Eason-zz** [comment]
> gigaword_chn.all.a2b.uni.ite50.vec/gigaword_chn.all.a2b.bi.ite50.vec/ctb.50d.vec/sgns.merge.word从readme中能够找到这四个，还缺上边的yangjie_word_char_mix.txt，不知道有没有遗漏，老哥方便给个链接吗

这个文件sgns.merge.word在哪里啊

**Comment by DavidJamesFY** [comment]
> > 懂了懂了，是程序生成的
> 
> 对的，不好意思，我刚才误导你了，我自己刚才想删掉cache，再验证一下的，哪知道不怎么顺利，哈哈哈~

> > 懂了懂了，是程序生成的
> 
> 对的，不好意思，我刚才误导你了，我自己刚才想删掉cache，再验证一下的，哪知道不怎么顺利，哈哈哈~

老铁  有预测代码吗

**Comment by 1921530438** [comment]
> 处理后生成的这个txt文件无法打开是怎么回事啊，一打开就无响应
您好，这个文件是程序自动生成的，那是运行的哪个py程序运行出来的呀？为什么我就是没有，希望帮帮我

**Comment by LawsonAbs** [comment]
> 
> 
> > 处理后生成的这个txt文件无法打开是怎么回事啊，一打开就无响应
> > 您好，这个文件是程序自动生成的，那是运行的哪个py程序运行出来的呀？为什么我就是没有，希望帮帮我

建议把readme 多读几遍

**Comment by guang11644331** [comment]
问下这个问题要怎么解决呢？ ValueError: Cannot recognize data/pretrain/chinese/yangjie_word_char_mix.txt

**Comment by zdgithub** [comment]
> > yangjie_word_char_mix.txt，老哥，请问这个文件在哪里可以找到
> 
> 这个文件是由程序自动下载的，程序运行起来就会加载出来。

请问是从代码哪里看出来会自动下载这个文件呢？感谢

**Comment by LeeSureman** [comment]
> > > yangjie_word_char_mix.txt，老哥，请问这个文件在哪里可以找到
> > 
> > 
> > 这个文件是由程序自动下载的，程序运行起来就会加载出来。
> 
> 请问是从代码哪里看出来会自动下载这个文件呢？感谢

在preprocess.py里

char_f = open(yangjie_rich_pretrain_unigram_path,'r')

output_f = open(yangjie_rich_pretrain_char_and_word_path,'w')

lexicon_lines = lexicon_f.readlines()

**Comment by zdgithub** [comment]
> > > > yangjie_word_char_mix.txt，老哥，请问这个文件在哪里可以找到
> > > 
> > > 
> > > 这个文件是由程序自动下载的，程序运行起来就会加载出来。
> > 
> > 
> > 请问是从代码哪里看出来会自动下载这个文件呢？感谢
> 
> 在preprocess.py里
> 
> char_f = open(yangjie_rich_pretrain_unigram_path,'r')
> 
> output_f = open(yangjie_rich_pretrain_char_and_word_path,'w')
> 
> lexicon_lines = lexicon_f.readlines()

嗯嗯，不好意思刚看到，非常感谢！
