### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by Jiangyangya** [LeeSureman/Flat-Lattice-Transformer#27]
您好，我想请问一下，我这边运行flat_main.py 后fastNLP_module提示fastNLP.modules.utils包中can not import name 'get_file_name_base_on_postfix'是什么情况，不是很懂这里的原因

**Comment by ywwhxxtw** [comment]
你好，我也遇到了同样的问题，想问一下你解决了吗？

**Comment by ywwhxxtw** [comment]
已解决，版本问题

**Comment by Eason-zz** [comment]
> 已解决，版本问题

能详细说明一下吗

**Comment by Jiangyangya** [comment]
> > 已解决，版本问题
> 
> 能详细说明一下吗

是fastnlp版本问题，这里用的是0.5.0，最好在装包时指定版本，我之前装的是0.5.5版本，然后有一个函数调用在包里导入不了，看了文档是发现版本不同存放位置有更改
