### ISSUE TITLE
NotADirectoryError: `logs` is not exist.

### ISSUE THREAD

**Issue by Eason-zz** [LeeSureman/Flat-Lattice-Transformer#28]
按照 readme 文件 运行V0中的fla_python.py文件后，出现了这个错误，想要请问一下这是什么情况

**Comment by Kouin** [comment]
新建一个log文件夹

**Comment by Eason-zz** [comment]
> 新建一个log文件夹

谢谢，我先试试

**Comment by Eason-zz** [comment]
> 新建一个log文件夹

还是不行啊，建立log.py后仍然是这个错误

**Comment by LawsonAbs** [comment]
> 
> 
> > 新建一个log文件夹
> 
> 还是不行啊，建立log.py后仍然是这个错误

老哥，是新建logs文件夹，不是log.py 文件。。。。。。。
再者，这个项目不大适合新手~

**Comment by Eason-zz** [comment]
> > > 新建一个log文件夹
> > 
> > 
> > 还是不行啊，建立log.py后仍然是这个错误
> 
> 老哥，是新建logs文件夹，不是log.py 文件。。。。。。。
> 再者，这个项目不大适合新手~

没办法，老师让做这个项目😂😂

**Comment by maturecat** [comment]
> > > > 新建一个log文件夹
> > > 
> > > 
> > > 还是不行啊，建立log.py后仍然是这个错误
> > 
> > 
> > 老哥，是新建logs文件夹，不是log.py 文件。。。。。。。
> > 再者，这个项目不大适合新手~
> 
> 没办法，老师让做这个项目😂😂

解决了吗？同样遇到这个问题了

**Comment by maturecat** [comment]
> > > 新建一个log文件夹
> > 
> > 
> > 还是不行啊，建立log.py后仍然是这个错误
> 
> 老哥，是新建logs文件夹，不是log.py 文件。。。。。。。
> 再者，这个项目不大适合新手
老哥新建log文件夹也不行啊
