### ISSUE TITLE
关于weibo数据集 

### ISSUE THREAD

**Issue by tyistyler** [LeeSureman/Flat-Lattice-Transformer#31]
作者您好，请问您在论文中使用的数据集是weiboNER.conll.train还是weiboNER_2nd_conll.train呢？

**Comment by leona-hub** [comment]
你知道了么，我也没弄清楚

**Comment by tyistyler** [comment]
weiboNER_2nd_conll.train是新的，用的这个

**Comment by Xu-ys** [comment]
> 作者您好，请问您在论文中使用的数据集是weiboNER.conll.train还是weiboNER_2nd_conll.train呢？
你好！可以提供一下weibo、Resume、MSRAN、之中的数据集吗？
