### ISSUE TITLE
ImportError: cannot import name '_get_file_name_base_on_postfix' from 'fastNLP.modules.utils'

### ISSUE THREAD

**Issue by ArlanCooper** [LeeSureman/Flat-Lattice-Transformer#36]
在调用fastNLP_module.py 的时候报这个错,报错地方:
from fastNLP.modules.utils import _get_file_name_base_on_postfix

我去fastNLP.modules.utils 这个里面找了，确实没有这个方法，是因为fastNLP的版本问题吗？还是其他什么原因呢

**Comment by geekjuruo** [comment]
pip uninstall fastNLP
pip install fastNLP==0.5.0

**Comment by LeeSureman** [comment]
> pip uninstall fastNLP
> pip install fastNLP==0.5.0

感谢回复

**Comment by ArlanCooper** [comment]
> pip uninstall fastNLP
> pip install fastNLP==0.5.0

感谢，已经修改成功
