### ISSUE TITLE
bert的实现

### ISSUE THREAD

**Issue by wangshuo6699** [LeeSureman/Flat-Lattice-Transformer#6]
你好，请问论文中是如何实现 Flat-Lattice 和BERT的结合，①是修改BERT的Transformer结构？②还是BERT只提供了char级别的embedding，然后在bert输出隐藏表示后进行FLAT的操作？

**Comment by LawsonAbs** [comment]
请问你是怎么理解的呢？小白请教~

**Comment by C929-x** [comment]
V1版本就是结合了bert吗
