### ISSUE TITLE
catch这里出错了，删除后cache后重新跑还是会有同样的Traceback

### ISSUE THREAD

**Issue by s1162276945** [LeeSureman/Flat-Lattice-Transformer#67]
Save cache to cache\weibo_trainClip:Truebgminfreq_1char_min_freq_1word_min_freq_1only_train_min_freqTruenumber_norm0load_dataset_seed100.
用的词表的路径:D:/pycode/test/Flat-Lattice-Transformer/data/pretrain/chinese/ctb.50d.vec
Save cache to cache/yj.
Found 698668 out of 698670 words in the pre-training embedding.
Found 17734 out of 17831 words in the pre-training embedding.

==============================================================================

Traceback (most recent call last):
  File "flat_main.py", line 291, in <module>
    only_train_min_freq=args.only_train_min_freq)
  File "D:\Anaconda3\lib\site-packages\fastNLP\core\utils.py", line 160, in wrapper
    with open(cache_filepath, 'wb') as f:
OSError: [Errno 22] Invalid argument: 'cache\\weibo_lattice_only_train:False_trainClip:True_norm_num:0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed
100'

**Comment by s1162276945** [comment]
我知道了，是windows 的文件名不支持带冒号的。已解决，谢谢。
=======================================

**Comment by tomatowithpotato** [comment]
> # 我知道了，是windows 的文件名不支持带冒号的。已解决，谢谢。

老哥是咋解决的啊？求赐教

**Comment by lvjiujin** [comment]
> > # 我知道了，是windows 的文件名不支持带冒号的。已解决，谢谢。
> 
> 老哥是咋解决的啊？求赐教

将flat_main.py中的下面的这行代码中的所有的":"替换成'-'即可。
`
cache_name = os.path.join('cache',(args.dataset+'_lattice'+'_only_train{}'+
                          '_trainClip:{}'+'_norm_num:{}'
                                   +'char_min_freq{}'+'bigram_min_freq{}'+'word_min_freq{}'+'only_train_min_freq{}'
                                   +'number_norm{}'+'lexicon_{}'+'load_dataset_seed{}')
                          .format(args.only_lexicon_in_train,
                          args.train_clip,args.number_normalized,args.char_min_freq,
                                  args.bigram_min_freq,args.word_min_freq,args.only_train_min_freq,
                                  args.number_normalized,args.lexicon_name,load_dataset_seed))
`

**Comment by tomatowithpotato** [comment]
> > > # 我知道了，是windows 的文件名不支持带冒号的。已解决，谢谢。
> > 
> > 
> > 老哥是咋解决的啊？求赐教
> 
> 将flat_main.py中的下面的这行代码中的所有的":"替换成'-'即可。 `cache_name = os.path.join('cache',(args.dataset+'_lattice'+'_only_train{}'+ '_trainClip:{}'+'_norm_num:{}' +'char_min_freq{}'+'bigram_min_freq{}'+'word_min_freq{}'+'only_train_min_freq{}' +'number_norm{}'+'lexicon_{}'+'load_dataset_seed{}') .format(args.only_lexicon_in_train, args.train_clip,args.number_normalized,args.char_min_freq, args.bigram_min_freq,args.word_min_freq,args.only_train_min_freq, args.number_normalized,args.lexicon_name,load_dataset_seed))`

虽然之前已经发现了，但还是感谢老哥！

**Comment by C929-x** [comment]
Traceback (most recent call last):
  File "E:\yan\chong\daimaDemo\Flat-Lattice-Transformer-master\Flat-Lattice-Transformer-master\V0\flat_main.py", line 290, in <module>
    datasets, vocabs, embeddings = equip_chinese_ner_with_lexicon(datasets, vocabs, embeddings,
  File "D:\Anaconda3\lib\site-packages\fastNLP\core\utils.py", line 160, in wrapper
    with open(cache_filepath, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cache\\weibo_lattice_only_train#False_trainClip#True_norm_num#0char_min_freq1bigram_min_freq1word_min_freq1only_train_min_freqTruenumber_norm0lexicon_yjload_dataset_seed100'

修改后出现这个问题，请问你们有出现过吗，如何解决
