### ISSUE TITLE
MSRA复现问题

### ISSUE THREAD

**Issue by mx8435** [LeeSureman/Flat-Lattice-Transformer#74]
1. 论文中FLAT+BERT的F1 96.08是有clip 200吗？在多大的卡上跑的？我在16g卡上oom了。
2. --train_clip这个参数需要跟preprocess.py中的--clip_msra一起使用吧?
2. V1中的load_msra_ner_without_dev方法找不到。preprocess.py生成的文件是"_clip2"后缀，而load_data中用的是"_clip1"。

**Comment by LeeSureman** [comment]
1.应该有的，12g的1080ti
2.train_clip会根据dataset自动修改，不需要手动改
3.改用load_msra_ner_1就好了

**Comment by QianGuYiDi** [comment]
> 1. 论文中FLAT+BERT的F1 96.08是有clip 200吗？在多大的卡上跑的？我在16g卡上oom了。
> 2. --train_clip这个参数需要跟preprocess.py中的--clip_msra一起使用吧?
> 3. V1中的load_msra_ner_without_dev方法找不到。preprocess.py生成的文件是"_clip2"后缀，而load_data中用的是"_clip1"。

针对第三个问题中的：preprocess.py生成的文件是"_clip2"后缀，而load_data中用的是"_clip1"。想问一下是不是把preprocess.py中的_clip2改为_clip1就可以了

**Comment by QianGuYiDi** [comment]
或者把load_data.py中的
def load_msra_ner_1(path,char_embedding_path=None,bigram_embedding_path=None,index_token=True,train_clip=False,
                              char_min_freq=1,bigram_min_freq=1,only_train_min_freq=0):
    from fastNLP.io.loader import ConllLoader
    from utils import get_bigrams
    if train_clip:
        train_path = os.path.join(path, 'train_dev.char.bmes_clip1')
        test_path = os.path.join(path, 'test.char.bmes_clip1')
    else:
        train_path = os.path.join(path,'train_dev.char.bmes')
        test_path = os.path.join(path,'test.char.bmes')

    loader = ConllLoader(['chars','target'])
    train_bundle = loader.load(train_path)
    test_bundle = loader.load(test_path)
    这段代码中的_clip1改为_clip2
