### ISSUE TITLE
请问当前 flat_main.py 里的默认参数，就是论文里描述的模型结构吗？

### ISSUE THREAD

**Issue by nefujiangping** [LeeSureman/Flat-Lattice-Transformer#8]
请问使用当前`flat_main.py`里的默认参数，模型结构就是论文里 “3.2 Relative Position Encoding of Spans” 所描述的模型结构吗？
[flat_main.py 116行](https://github.com/LeeSureman/Flat-Lattice-Transformer/blob/a1cda46fb9796e270c074707bf03dce0d8228370/V0/flat_main.py#L116)：
```
parser.add_argument('--four_pos_fusion',default='ff_two',choices=['ff','attn','gate','ff_two','ff_linear'],
```
[modules.py 110行](https://github.com/LeeSureman/Flat-Lattice-Transformer/blob/a1cda46fb9796e270c074707bf03dce0d8228370/V0/modules.py#L110)
```
if self.four_pos_fusion == 'ff_two':
    pe_2 = torch.cat([pe_ss,pe_ee],dim=-1)
```
这里我理解是只使用了4个相对位置特征([pe_ss,pe_se,pe_es,pe_ee])中的两个[pe_ss,pe_ee]，而论文“3.2 Relative Position Encoding of Spans”用了4个特征。不知道是否是我对代码解读有误？

**Comment by LeeSureman** [comment]
这里是只用到了两个特征，主要是出于在效果等价的情况下节省显存的考虑，因为我们现在用的是一层的transformer嘛，过了transformer之后得到的词的表示我们是不需要的，只需要用字的表示去做标签分类，由于字的长度始终是1，所以ss和ee就足以携带字和词之间的位置关系了。但是对于两层及以上的transformer，ss和ee不足以建模词与词之间的位置关系，这个时候就需要用到4个相对位置特征了

**Comment by nefujiangping** [comment]
好的，明白啦，谢谢你的回复～

**Comment by LawsonAbs** [comment]
> 后得到的词的表示我们是不需要的，只需要用字的表示去做标签分类，由于字的长度始终是1，所以ss和ee就足以携带字和词之间的位置关系了。但是对于两层及以

为什么“过了transformer之后得到的词的表示我们是不需要的”？？？ 是因为词的embedding都是从字典中找到训练好的表示吗？

**Comment by LeeSureman** [comment]
> > 后得到的词的表示我们是不需要的，只需要用字的表示去做标签分类，由于字的长度始终是1，所以ss和ee就足以携带字和词之间的位置关系了。但是对于两层及以
> 
> 为什么“过了transformer之后得到的词的表示我们是不需要的”？？？ 是因为词的embedding都是从字典中找到训练好的表示吗？

我们最终只需要在字token上做序列标注
